apiVersion: v1
kind: Service
metadata:
  name: cloudmart-api-service
  namespace: cloudmart
spec:
  type: NodePort             # "Open a door to the outside world"
  selector:
    app: cloudmart-api       # "Find workers with this ID tag"
  ports:
    - protocol: TCP
      port: 80               # "The door number on the Front Desk"
      targetPort: 80         # "The door number on the actual worker (Pod)"
      nodePort: 30007        # "The specific door on your laptop to enter through"
