apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Helm helper: b64enc encodes your plain text password into Base64 (which K8s requires)
  ROOT_PASSWORD: {{ .Values.database.password | b64enc | quote }}
