apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }} # <--- Correct
spec:
  replicas: {{ .Values.productService.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: {{ .Values.productService.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        # --- ADDED THIS BLOCK ---
        resources:
{{ toYaml .Values.productService.resources | indent 10 }}
        # -------------------------
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
        - name: DB_NAME
          value: "cloudmart"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }} # <--- Changed to template for consistency
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
