apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{ .Values.userService.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
        - name: DB_NAME
          value: "cloudmart"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
